juju/juju-crashdump

- juju-crashdump
Useful for automated testing frameworks, which don't necessarily want to
create a huge tarball each time.
@johnsca, @kwmonroe Thinking about this, I think that it makes sense to include /var/lib/juju in juju-crashdump when it is run manually. You are trying to diagnose a problem, and saving off the state of the /var/lib/juju dir is useful for that diagnosis.
I don't think that it's so useful that it needs to be included in the automated tests, though. If you agree with this approach, the next step is to pass "-s" in matrix (and bundletester).
... and the next step after that might be to only crashdump when we have a test failure.
> Added an option to skip adding /var/lib/juju to juju-crashdump.

- juju-crashdump
When tested on a bundle:openstack-base deployment, the xz-compressed tarball
was 25% of the gzip-compressed one (40M->10M).
> Use xz compression instead of gzip

- juju-crashdump
Reported by pyflakes:
juju-crashdump:12: 'shlex' imported but unused
> Remove unused import

- .travis.yml
- jujucrashdump/crashdump.py
- setup.py
- snapcraft.yaml
- tests/assets/good_juju_status.yaml
- tests/test_juju_status_parser.py
- tox.ini
Improvements:
* Make crashdump importable to other python projects -- move it to an importable name
* Has a test
* flake and testing via tox
* travis integration
Didn't mean for this to be as large as it is, but it just kept rolling...
> better project layout, including: tests/flake/tox/travis

- jujucrashdump/crashdump.py
- tests/assets/bad_juju_status.yaml
- tests/test_juju_status_parser.py
Because some machines may have no units, as shown in https://github.com/juju/juju-crashdump/issues/6
Also adds a testcase given that juju status.
This changes the default layout slightly, to be based on machine names rather than ips, although the ips and unit names are still symlinks to the correct directories.
They are now laid out as follows:
```
/
/debug_log.txt
/juju_status.yaml
/0/baremetal/var/log...
/0/lxd/0/var/log...
/0/lxd/1/var/log...
/1/baremetal/var/log...
```
> Use machine name rather than a unit name for scp

- jujucrashdump/crashdump.py
This prevents checking for a string in a None type.
> Survive without excludes.

- jujucrashdump/crashdump.py
On larger models, this timeout value is too short. Making it
user specified allows flexibility.
This fixes issue #16.
> Allow overriding default timeout of 45 seconds.

- jujucrashdump/addons.yaml
- jujucrashdump/crashdump.py
This allows us to collect output about what services are
listening on network ports during a run.
Closes #21
> Collect which applications are listening

- jujucrashdump/addons.py
When running addons, juju fails to scp files to each machine
because "ERROR exit status 1 (scp: error: unexpected filename: .)"
This creates a list of files and directories in the current working
directory, and recursivly pushes them to the host.
> Correct pathing for addons juju scp.

- jujucrashdump/crashdump.py
The data in /var/lib/juju/agents is generally very small and
can easily be included into every crashdump.
Fixes: #29
> Add /var/lib/juju/agents to --small dumps

- jujucrashdump/addons.py
- jujucrashdump/crashdump.py
Allow the user to use addons from the default addons.yaml and their own addons.yaml.
> Use multiple addons files

- jujucrashdump/crashdump.py
Model-config seems useful for any deployment
storage and storage-pool are most useful for k8s deployments, but are small and don't hurt to include.
> Add model-config, storage, and storage-pool to crashdumps.

- jujucrashdump/crashdump.py
This reverts commit 8a557f4d478fc44d4ac1d2762b9428e8e7e9f492.
Turns out /var/lib/juju/agents adds several GB's to crashdumps
on large FCB deployments.
Fixes issue #37.
> Revert "Add /var/lib/juju/agents to --small dumps"

- jujucrashdump/crashdump.py
/etc/cloud contains two things of interest:
a.) build.info which identifies ubuntu builds with a name and serial.
b.) cloud-init config files which affect cloud-init's behavior.
/var/lib/cloud/seed contains the datasource NoCloud information that
is provided for lxd instances.
> collect /etc/cloud and /var/lib/cloud/seed.

- jujucrashdump/addons.yaml
- jujucrashdump/crashdump.py
juju_engine_report is run for each unit and for the machine itself
and stored in a juju_introspection directory.
Configs are generated for each application and saved on in a
config dir for each machine.  Since the addon is optional,
the concern for private data can be assessed by the user.  See
lp:#1826449 for hiding private data in juju config.
> Add addons for juju_engine_report and juju config.

- jujucrashdump/crashdump.py
- tox.ini
When unit is in error or blocked state juju run will not connect.
Using ssh instead allows to collect data regardless of juju agent
status.
solves #28 amd #26
> replace juju run and juju scp with ssh and scp

- jujucrashdump/addons.py
- jujucrashdump/crashdump.py
- snapcraft.yaml
- Switch to yaml.safe_load()
- Fix ssh/scp failing by using the ubuntu user explicitly
- Switch snap to build from core18 base
Built and tested locally. Fixes these failures:
```
$ juju-crashdump -a debug-layer -a config
/snap/juju-crashdump/143/lib/python3.5/site-packages/jujucrashdump/addons.py:48: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
addon_specs = yaml.load(addons_file)
Command "timeout 45s ssh -o StrictHostKeyChecking=no -i ~/.local/share/juju/ssh/juju_id_rsa 54.237.153.136 sudo 'mkdir -p /tmp/994bee8b-ef0d-4cc0-aee9-930333a563f4/cmd_output;sudo netstat -taupn | grep LISTEN 2>/dev/null | sudo tee /tmp/994bee8b-ef0d-4cc0-aee9-930333a563f4/cmd_output/listening.txt …
```
> Fix ssh/scp and yaml warning

- jujucrashdump/crashdump.py
This prevents juju-crashdump from crashing when it hits a
container in pending state. Instead, it just skips over it.
> Skip containers that don't have ip-addresses.

- jujucrashdump/addons.yaml
Fixes https://github.com/juju/juju-crashdump/issues/50
---
This allows those addons to use the `jq` binary that's bundled with the snap.
I don't know why, but when it was like this:
```
juju config $app >> $app-config.yaml
```
I was getting this output from the script during debug:
```
ERROR write /dev/stdout: permission denied
```
But when I changed it to this:
```
juju config $app | cat >> $app-config.yaml
```
it started working. Yay?!
---
Tested with these changes by running:
```
juju-crashdump --small -a debug-layer -a config
```
against a live Charmed Kubernetes cluster. I confirmed that the resulting .tar.gz included debug action output and application config.
> Fix config and debug-layer addons

- jujucrashdump/crashdump.py
Knowing which rules are present in the system is useful for debugging
issues like LP: #1883585.
> Collect udev rules

- jujucrashdump/crashdump.py
This is useful to see why mongodb is crashing.
> Grab juju-db logs by default.

- jujucrashdump/crashdump.py
A bug/request has been raised against Juju project as LP: #1907515.
However, explicitly having dates always is still nice to have in
juju-crashdump as the log may be stretched across multiple days.
Closes: #62
> Explicitly include dates in debug-log

- jujucrashdump/crashdump.py
`--max-file-size` may cause an unexpected behavior from an user point of
view since it doesn't collect larger files out of the box. It would be
better to expose the default value explicitly in the help output so one
can adjust it per their need.
> Include some default values explicitly in the help output

- jujucrashdump/crashdump.py
This way, when you untar it, it doesn't dump a million
files in your current directory.
> Collect crashdump in a directory.

- jujucrashdump/crashdump.py
Method was created in a previous commit but it was not called.
> call run_psaux()

- jujucrashdump/crashdump.py
- tests/test_jujucrashdump_crashdump.py
When juju-crashdump is run against a secured environment (CIS hardened), we run into all kinds of different permission errors.
This change adds an option to specify where to generate the crashdump on the units so that we can put it somewhere sane like /home/ubuntu while defaulting to the original behavior of dumping things in /tmp.
> Add option to specify unit-dump-location

- jujucrashdump/crashdump.py
Currently the code reports that the command failed, but the reason it failed is not reported, this logs that error as well.
> Log subprocess failures during collection

- jujucrashdump/addons.yaml
Netstat is deprecated and does not ship by default anymore. Also small drive-by simplification by filtering for LISTEN directly
> Use ss instead of netstat to get listening ports

- .github/workflows/tox.yml
- jujucrashdump/addons.py
- jujucrashdump/crashdump.py
- requirements.txt
- snapcraft.yaml
- tests/test_jujucrashdump_crashdump.py
- tox.ini
Since recently, workloads on OpenStack controllers do not get a public IP. In order to still get the crashdumps for workloads on OpenStack we need to use the `--proxy` option when using `juju scp` or `juju ssh`. We need to make a proxy jump through the juju controllers for vanilla ssh commands. This requires slightly different ssh-key handling, which is assisted by the `ssh-agent-setup` package.
The unittests are updated from nose to pytest and the formatter `black` is run against all .py files.
> Use ssh controller proxy

- snapcraft.yaml
The current build of the snap only works on jammy, some updates to the snapcraft definition are necessary to get it running on focal too.
> Make snap compatible with focal
